version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: issuetracker-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: issuetracker
      POSTGRES_USER: issuetracker
      POSTGRES_PASSWORD: issuetracker
    volumes:
      - issuetracker-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    container_name: my-rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: issuetracker
      RABBITMQ_DEFAULT_PASS: issuetracker

  redis:
    image: redis:7.2.4-alpine
    container_name: issuetracker-redis-container
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: issuetracker
    volumes:
      - issuetracker-redis-data:/data
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev

volumes:
  issuetracker-postgres-data:
  issuetracker-redis-data:
  smtp4dev-data:
