CREATE TABLE issue_tracker_role
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(50)                             NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(50),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    description        VARCHAR(255),
    active             BIT DEFAULT B'1'                        NOT NULL,
    CONSTRAINT pk_issue_tracker_role PRIMARY KEY (id)
);

ALTER TABLE issue_tracker_role
    ADD CONSTRAINT uc_d4c12ebf15522123f6d839d31 UNIQUE (name);

CREATE INDEX idx_f4a2b749adeab8dc33a520a21 ON issue_tracker_role (name, active);

CREATE TABLE issue_tracker_user
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(50)                             NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(50),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    first_name         VARCHAR(50),
    last_name          VARCHAR(50),
    login              VARCHAR(50)                             NOT NULL,
    phone_number       VARCHAR(255)                            NOT NULL,
    email              VARCHAR(254),
    password_hash      VARCHAR(200),
    activated          BIT DEFAULT B'1'                        NOT NULL,
    CONSTRAINT pk_issue_tracker_user PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (role_id, user_id)
);

ALTER TABLE issue_tracker_user
    ADD CONSTRAINT uc_issue_tracker_user_email UNIQUE (email);

ALTER TABLE issue_tracker_user
    ADD CONSTRAINT uc_issue_tracker_user_login UNIQUE (login);

ALTER TABLE issue_tracker_user
    ADD CONSTRAINT uc_issue_tracker_user_phone_number UNIQUE (phone_number);

CREATE INDEX idx_6376184f95b1ac8fa87ae369e ON issue_tracker_user (email, login, first_name, activated);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES issue_tracker_role (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES issue_tracker_user (id);